# Generated by Django 3.0.1 on 2019-12-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questtion_text',
            new_name='question_text',
        ),
    ]
