# Generated by Django 3.0.1 on 2019-12-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191229_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choise_textt',
            new_name='choice_text',
        ),
    ]
