# Generated by Django 3.0.1 on 2019-12-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191229_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
