# Generated by Django 3.0.2 on 2020-03-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocklog', '0007_auto_20200304_1834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stream',
            new_name='StreamSong',
        ),
    ]
