# Generated by Django 3.0.3 on 2020-03-31 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rocklog', '0008_auto_20200304_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rocklog.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
