# Generated by Django 3.0.3 on 2020-04-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocklog', '0009_savedsong'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamSong',
            new_name='StreamEntry',
        ),
    ]
