# Generated by Django 3.0.3 on 2020-04-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocklog', '0010_auto_20200403_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamentry',
            options={'verbose_name_plural': 'Stream Entries'},
        ),
    ]
