# Generated by Django 3.0.3 on 2020-04-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocklog', '0011_auto_20200403_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsong',
            name='date',
        ),
    ]
