# Generated by Django 3.0.3 on 2020-04-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocklog', '0013_auto_20200406_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
